# Utilisation de l'image Python basée sur Alpine
FROM python:3.11-alpine

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers nécessaires
COPY requirements.txt ./

# Installe les dépendances
RUN apk add --no-cache gcc musl-dev python3-dev && \
    pip install --no-cache-dir -r requirements.txt

# Copie le reste du code
COPY . .

# Expose le port de l’API Flask
EXPOSE 5000

# Commande pour démarrer Flask en mode développement
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

