"""newschema

Revision ID: 65f784a1b7a4
Revises: 
Create Date: 2025-05-15 16:42:19.126560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f784a1b7a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('`order`', sa.Integer(), nullable=True),
    sa.Column('ref_name', sa.String(length=50), nullable=True),
    sa.Column('ref_parent', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ref_parent'], ['category.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('role',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('schedule_times',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('role_hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('access', sa.String(length=50), nullable=True),
    sa.Column('ref_role', sa.String(length=50), nullable=True),
    sa.Column('ref_access', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.role'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.role'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('publication',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('on_line', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ref_author', sa.String(length=50), nullable=True),
    sa.Column('ref_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ref_author'], ['user.email'], ),
    sa.ForeignKeyConstraint(['ref_category'], ['category.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_page_container',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('`order`', sa.Integer(), nullable=True),
    sa.Column('ref_name', sa.String(length=100), nullable=True),
    sa.Column('ref_publication', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ref_publication'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('publication_content',
    sa.Column('publication', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['publication'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('publication', 'lastname', 'firstname')
    )
    op.create_table('publication_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['photo'], ['photo.path'], ),
    sa.ForeignKeyConstraint(['publication'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication', sa.String(length=100), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('ref_day', sa.String(length=10), nullable=True),
    sa.Column('ref_email', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['publication'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['ref_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_schedule')
    op.drop_table('publication_photo')
    op.drop_table('publication_event')
    op.drop_table('publication_content')
    op.drop_table('home_page_container')
    op.drop_table('publication')
    op.drop_table('user')
    op.drop_table('role_hierarchy')
    op.drop_table('schedule_times')
    op.drop_table('role')
    op.drop_table('photo')
    op.drop_table('contact_info')
    op.drop_table('category')
    # ### end Alembic commands ###
